AGW-3197: Add public key obtention info to JWT doc.
mulesoft/docs-api-manager pull request #114
Opened 2019-07-02 18:19 UTC by JaatadiaMulesoft

2019-07-02 19:26 UTC, balbifm requested changes

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +The policy uses public rsa key in pem format. In this section we explain how to obtain the public.pem file that contains said key.
RSA

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +Remember that once the public.pem key is obtained, before pasting it to the policy configuration to remove the *-----BEGIN PUBLIC KEY-----* header, and the *-----END PUBLIC KEY-----* footer.
policy configuration,

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +Remember that once the public.pem key is obtained, before pasting it to the policy configuration to remove the *-----BEGIN PUBLIC KEY-----* header, and the *-----END PUBLIC KEY-----* footer.
header and instead of header, and

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +| . Extract the private key from the pem certificate `openssl x509 -inform pem -in cert.pem -pubkey -noout > public.pem`
PEM

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +The policy uses public rsa key in pem format. In this section we explain how to obtain the public.pem file that contains said key.
PEM

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +| . Extract the private key from the pem certificate `openssl x509 -inform pem -in cert.pem -pubkey -noout > public.pem`
public instead of private

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +| . Extract the private key from the pem certificate `openssl x509 -inform der -in cert.crt -pubkey -noout > public.pem`
public instead of private

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +. Extract the private key from the pem certificate `openssl x509 -inform der -in cert.crt -pubkey -noout > public.pem`
public instead of private

2019-07-02 19:26 UTC, balbifm commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +== Accessing propagated claims
This should be merged with the == Claim Propagation section in line 74 (currently at least)

2019-07-12 19:32 UTC, priyaayyar commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +Once the policy parses and validates the JWT, the claims are propagated to downstream policies and flows through the *claims* property in the authentication object.
After the policy parses and validates the JWT (use full form of JWT), the claims are propagated to downstream policies and flow, by using the *claims* property in the authentication object.

2019-07-12 19:35 UTC, priyaayyar commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +To access the claim values you can use the following Dataweave 2.0 expression replacing `<claimName>` with the name of the desired claim to access:
To access claim values, use the following Dataweave 2.0 expression:
`#[authentication.properties.claims.<claimName>]`,
where <claimName> must be the name of the claim that you want to access.

2019-07-12 19:50 UTC, priyaayyar commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +The policy uses public rsa key in pem format. In this section we explain how to obtain the public.pem file that contains said key.
The policy uses a public RSA key in .pem format. This section describes how to obtain the public .pem file that contains the key.

2019-07-12 19:54 UTC, priyaayyar commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +Remember that once the public.pem key is obtained, before pasting it to the policy configuration to remove the *-----BEGIN PUBLIC KEY-----* header and the *-----END PUBLIC KEY-----* footer.
Before applying the public.pem key to the policy configuration, ensure that you remove the following header and footer:
.  *-----BEGIN PUBLIC KEY-----* header 
. *-----END PUBLIC KEY-----* footer

2019-07-16 15:18 UTC, priyaayyar approved these changes

2019-07-16 19:37 UTC, balbifm approved these changes

2019-07-16 19:37 UTC, merged