AGW-3184: complete custom policy doc
mulesoft/docs-api-manager pull request #115
Opened 2019-07-02 20:41 UTC by JaatadiaMulesoft

2019-07-03 16:42 UTC, balbifm requested changes

2019-07-03 16:42 UTC, balbifm commented on modules/ROOT/pages/custom-policy-uploading-to-exchange.adoc
> +. Search for your organization's ID to use in the following steps.
Make reference to Anypoint at some point. No context otherwise

2019-07-03 16:42 UTC, balbifm commented on modules/ROOT/pages/custom-policy-uploading-to-exchange.adoc
> +. Additionally, add the following build plugins:
Add brief explanation of the plugins, it was asked a couple of times in slack.

2019-07-04 17:20 UTC, balbifm approved these changes

2019-07-16 15:33 UTC, priyaayyar approved these changes

2019-07-16 15:33 UTC, priyaayyar commented
Edit changes made directly.

2019-07-16 15:33 UTC, merged