AGW-3597: Document new http-transform operations added in 3.1.0.
mulesoft/docs-api-manager pull request #152
Opened 2019-10-15 18:24 UTC by JaatadiaMulesoft

2019-10-16 01:33 UTC, balbifm requested changes

2019-10-16 01:33 UTC, balbifm commented on modules/ROOT/pages/http-policy-transform.adoc
> +This operation is used to inject headers in the request. To use this operation, you must initiate a call from:
We should make it clear why we added this operation.

2019-10-18 18:53 UTC, priyaayyar approved these changes

2019-10-22 17:42 UTC, balbifm approved these changes

2019-10-22 17:42 UTC, merged