DOCS-8008 made edits
mulesoft/docs-api-manager pull request #250
Opened 2020-05-08 22:07 UTC by priyaayyar

Added comment entry

2020-05-12 21:28 UTC, nahuel-dallavecchia requested changes

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
> +//Nahuel please review the whole topic and suggest changes
Consider saying API endpoint instead of API instance endpoint (for consistency with other docs).

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  You can set up one of the following types of endpoint management:
API endpoint management?

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  * Direct management of the endpoint: Basic endpoint
Perhaps a simpler title -> "Basic endpoint"
and then, a one line description of what is that.

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
> +Set up a basic endpoint.
Considering that it's already in the corresponding section, perhaps the title should be: Setup or Configuration?

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  * Management by proxy: Endpoint with proxy
Proxy endpoint?

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
Following statement is incorrect. Basic endpoint is when you have a Mule application with autodiscovery correctly defined against your API. Proxy endpoint is when you either you have a Mule application where you cannot add the autodiscovery stuff or your API is implemented in a technology different than Mule. Policies only can be applied to Mule apps with autodiscovery, so in the latter case, you need an autogenerated proxy where policies can be applied and that it forwards correctly the request to the corresponding API (backend implementation).

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"In API Manager, click the version, or an instance of the API if you have more than once defined."

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"Add Consumer Endpoint" no consumer endpoint in the UI."Implementation URI" is the term that should be used instead (see UI).

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"Above API Configuration, in Add Consumer Endpoint" -> Implementation URI is within that section (see UI).

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
In general I would say review screenshot and match what we have currently in the UI with the actual explanation.

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
Remove specific Mule agent version from doc (ie "Mule Agent 1.9.0").

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"In *Implementation URI*, either enter the URL of the site that hosts the API or accept the default, a dummy URI." if Endpoint with Proxy is selected, the autogenerated proxy will never work in this way. If Basic endpoint selected, the implementation URI is informative. The actual link between API and API endpoint is done using autodisocvery. The same can be said about autogenerated proxies, the problem of using a fake implementation URI in this case is not about the link, but when that all requests handled by the proxy will fail when re sent to the fake impl URI.

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
IdP stands for Identity Provider (https://en.wikipedia.org/wiki/Identity_provider)

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"In *Advanced Options*, optionally assign an instance label for the proxy, or accept the label, and set a response timeout." Label and timeout are optional settings (the latter only when Proxy endpoint is selected).

2020-05-12 21:28 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  +
"For example, changing the path to `/users` makes the REST call to the service at the implementation URI `+http://jsonplaceholder.typicode.com/users+`." When you change the path of the proxy, makes the implementation endpoint to be called with what comes after the proxy path. For example:
Proxy path: /users
Impl URI: http://jsonplaceholder.typicode.com
Call proxy: http://<proxy host>:<proxy port>/users/hello -> Proxy will call impl endpoint using: http://jsonplaceholder.typicode.com/hello

2020-05-13 00:47 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +//Nahuel please review the whole topic and suggest changes
Done! Thanks!

2020-05-13 00:47 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
>  You can set up one of the following types of endpoint management:
Done! Thanks!

2020-05-13 00:49 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
>  * Direct management of the endpoint: Basic endpoint
Done! Thanks!

2020-05-13 00:51 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +Set up a basic endpoint.
Done! Thanks!

2020-05-13 00:51 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
>  * Management by proxy: Endpoint with proxy
Endpoint with proxy is better I feel.

2020-05-13 20:07 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configure-api-task.adoc
>  * Management by proxy: Endpoint with proxy
LGTM!

2020-05-14 04:49 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
>  +
Done! Thanks!

2020-05-18 17:19 UTC, kbostrom approved these changes
Edited

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +* Basic endpoint
```suggestion
* Basic API endpoint configuration
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +* Endpoint with proxy
```suggestion
* Proxy API endpoint configuration
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +Configure and directly manage a basic endpoint. Use this option when you have a Mule runtime Engine (Mule) application with autodiscovery correctly defined against your API.
```suggestion
Use this option to directly interact with a Mule application configured for autodiscovery.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +Use this option if you either have a Mule application for which cannot configure autodiscovery or if your API is implemented using a technology different than one used to develop Mule.
```suggestion
Use this option to interact by proxy with a Mule application that cannot be automatically discovered, either because it is not configured for autodiscovery or because it uses a technology different from that of the API. In this case, the proxy must be both automatically discoverable and able to correctly forward application requests to the API. This is known as _backend implementation_.
```
BUT...do we really need "or because it uses a technology different from that of the API"? It sounds to me like the real problem is that the app cannot be automatically discovered. Is that CAUSED by the different technologies? If so, that should be specified as the cause rather than a separate issue.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> += Configuring an API Endpoint in API Manager
I read the intro text about the two types of API endpoint management several times and suggested several rewordings before I realized that they should be reworded to address the API endpoint config and not the application config. So the "management" is not really managing the endpoint but rather configuring the endpoint to interact with the app either directly or by proxy. 
The original text changes the title of "configure" to text about "manage," and that is misleading, I think.
So the following are my final edits, based on what I finally figured out and I hope they make the text immediately more clear for the audience.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +You can set up one of the following types of API endpoint management:
```suggestion
How you configure your API endpoint to manage application requests depends on the relationship between your Mule application and your API:
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +You can apply policies only to Mule applications that are configured with autodiscovery. Therefore, for the endpoints with proxy option, you need an auto-generated proxy to which you can apply polici
See suggestion to merge this para into the para above it.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +To configure an API endpoint:
```suggestion
To configure your API endpoint:
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. In API Manager, click the version, or an instance of the API.
```suggestion
. In API Manager, click either the version number or instance of the API for which you want to configure an endpoint.
```
What does this look like? Is the user sometimes presented with version numbers and sometimes presented with some alternative ("instance")?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +.The diagram illustrates the inputs you must provide to create the API endpoint.
```suggestion
.The screen capture shows how to create and configure an endpoint for the selected API.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +image::create-instance-endpoint-midp.png[Create API Endpoint]
```suggestion
image::create-instance-endpoint-midp.png[Create and configure an API endpoint]
```
We must be clear here: is the user CREATING or CONFIGURING an endpoint? If both, that should be made clear in both the topic title and the intro text.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +<1> Add a tag for API endpoint.
Are these callouts supposed to be user actions or just identifiers? To make this one parallel with the following two:
```suggestion
<1> A tag for the API endpoint
```
However, what is a "tag"? Is this really a name or some other type of identifier?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +<2> The endpoint type: Basic or Proxy.
```suggestion
<2> The endpoint type: basic or proxy
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +<3> The client provider if you have configured an external client provider.
```suggestion
<3> The client provider, if you have configured an external client provider
```
Does this client provider need explaining?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +image::create-instance-endpoint-midp.png[Create API Endpoint]
Also...does this screencap show the entire process, including steps not yet described?
I would expect a screencap following Step 1 to illustrate Step 1, but it sounds like this illustrates the entire task.
Consider breaking up screencap into parts that illustrate each step, step by step.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +<1> Add a tag for API endpoint.
Why is this called out first when it appears to an optional step...at the END of this task?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +image::create-instance-endpoint-midp.png[Create API Endpoint]
Also, if including callouts in one big illustration, why give numbers to optional tag and client provider, but not the major steps?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. Optionally, specify the public-facing URL for the API in the *Implementation URI* field, for example: `+http://product.mydomain.com+`.
I wonder if this should be part of or subordinate to the first step?
```suggestion
. Optionally, specify the public-facing URL for the API in the *Implementation URI* field, for example, `+http://product.mydomain.com+`.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. Scroll to the bottom of the page to the *API Configuration* section.
```suggestion
. Scroll down to the *API Configuration* section.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +Use this option if you either have a Mule application for which cannot configure autodiscovery or if your API is implemented using a technology different than one used to develop Mule.
Is the app configured for autodiscovery, or the API?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +* *Endpoint With Proxy*: select a proxy deployment target CloudHub or Hybrid installation. Hybrid is a product for managing servers.
Suggest either fully defining in intro OR here, but not both.
Note the intro definition for proxy version does not match this one.

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. Select the *Mule version* box if you want to manage APIs in Mule 4 or above.
```suggestion
. Select the *Mule version* box if you want to manage APIs in Mule 4 or later.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +Otherwise, you can skip this step.
". If you are using the proxy configuration, in the *Implementation URI* field, specify the URL of the site that hosts the API."

You had "either" in the orig; did you mean "either accept the default or specify..."?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. From *Client provider*, select the identity provider (IdP) that you want to use to authenticate access to this API from registered client applications.
```suggestion
. In *Client provider*, select the identity provider (IdP) that you want to use to authenticate access to this API from registered client applications.
```
Isn't this optional, per callout <3> above?
Are these steps really in the order in which a user would perform them? It sounds like the user has to scroll up and down the page?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. Optionally, specify the public-facing URL for the API in the *Implementation URI* field, for example: `+http://product.mydomain.com+`.
Wait...using the *Implementation URI* field is mentioned again, later in this task. 
Is the user scrolling up and down?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +Otherwise, you can skip this step.
Also...this field is also mentioned above; is the user scrolling up and down?

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. If you selected the *Endpoint with proxy* option previously in this procedure, from the *Advanced Options*, optionally assign an instance label for the proxy, or accept the label, and set a respons
```suggestion
. If you selected *Endpoint With Proxy*, from *Advanced Options*, optionally accept the default or assign an instance label for the proxy, and set a response timeout.
```

2020-05-18 17:19 UTC, kbostrom commented on modules/ROOT/pages/configure-api-task.adoc
> +. Optionally, at the top of *API Configuration* section, click *ADD A TAG* to enter a tag name, for example: Released, to signal the status of an API version to users.
```suggestion
. Optionally, scroll up *API Configuration* and click *ADD A TAG* to enter a tag name (for example,`Released,`) to signal the status of the API version.
```

2020-05-18 20:21 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +* Basic endpoint
Done! Thanks!

2020-05-18 20:22 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +* Endpoint with proxy
Done! Thanks!

2020-05-18 20:24 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +Configure and directly manage a basic endpoint. Use this option when you have a Mule runtime Engine (Mule) application with autodiscovery correctly defined against your API.
Done! Thanks!

2020-05-18 20:41 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +You can set up one of the following types of API endpoint management:
Done! Thanks!

2020-05-18 20:44 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +To configure an API endpoint:
Done! Thanks!

2020-05-18 20:44 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> += Configuring an API Endpoint in API Manager
Ok Thanks!

2020-05-18 21:01 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. In API Manager, click the version, or an instance of the API.
No, the users are show both. An instance is associated to an API version. 
I'm saying this now:In API Manager, select the instance of the API for which you want to configure an endpoint.

2020-05-18 21:07 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. In API Manager, click the version, or an instance of the API.
Done! Thanks!

2020-05-18 21:08 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +.The diagram illustrates the inputs you must provide to create the API endpoint.
Done! Thanks!

2020-05-18 21:10 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +image::create-instance-endpoint-midp.png[Create API Endpoint]
That much detail not warranted. Other parts are very simple and evident. Done! Thanks!

2020-05-18 21:11 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +<1> Add a tag for API endpoint.
Done! Thanks!

2020-05-18 21:11 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +<2> The endpoint type: Basic or Proxy.
Done! Thanks!

2020-05-18 21:12 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +<3> The client provider if you have configured an external client provider.
Done! Thanks!

2020-05-18 21:16 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. Optionally, specify the public-facing URL for the API in the *Implementation URI* field, for example: `+http://product.mydomain.com+`.
Good catch! This is a remnant from the previous work. I removed the step from here. Done! Thanks!

2020-05-18 21:17 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. Scroll to the bottom of the page to the *API Configuration* section.
Keep to the bottom of the page, because it is really that. It was very hard for me to find where this section was. Done! Thanks!

2020-05-18 21:19 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +* *Endpoint With Proxy*: select a proxy deployment target CloudHub or Hybrid installation. Hybrid is a product for managing servers.
Shortened it here. But need the info when the users need to make the decision.

2020-05-18 21:20 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. Select the *Mule version* box if you want to manage APIs in Mule 4 or above.
Done! Thanks!

2020-05-18 21:21 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +Otherwise, you can skip this step.
Done! Thanks!

2020-05-18 23:57 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. From *Client provider*, select the identity provider (IdP) that you want to use to authenticate access to this API from registered client applications.
Done! Thanks!

2020-05-18 23:58 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. If you selected the *Endpoint with proxy* option previously in this procedure, from the *Advanced Options*, optionally assign an instance label for the proxy, or accept the label, and set a respons
Done! Thanks!

2020-05-18 23:59 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +. Optionally, at the top of *API Configuration* section, click *ADD A TAG* to enter a tag name, for example: Released, to signal the status of an API version to users.
Done! Thanks!

2020-05-19 13:41 UTC, nahuel-dallavecchia approved these changes

2020-05-19 17:46 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +Use this option if you either have a Mule application for which cannot configure autodiscovery or if your API is implemented using a technology different than one used to develop Mule.
API. No change needed here.

2020-05-19 17:46 UTC, priyaayyar commented on modules/ROOT/pages/configure-api-task.adoc
> +You can apply policies only to Mule applications that are configured with autodiscovery. Therefore, for the endpoints with proxy option, you need an auto-generated proxy to which you can apply polici
Done! Thanks!

2020-05-21 00:28 UTC, merged