made edits
mulesoft/docs-api-manager pull request #264
Opened 2020-06-22 18:25 UTC by priyaayyar

- Added note for oas3 support.
- Made edits for content that was inconsistent with the UI.

2020-06-22 19:34 UTC, sbehrends requested changes
Left some comments regarding some wording changes etc.
OAS3 Notices looks good.

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +. Select *API Administration* > *Manage API* > *Create a new API*.
Here you are changing the flow from "Manage API from Exchange" to "Create New API" is this change intended?

- "Manage API from Exchange": User is able to search and select an asset published in Exchange
- "Create New API": Will allow user to upload an asset to Exchange and Manage such assets in one step.

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +For example, set up version 1.0 of an API named `jsonplaceholder`:
Would this asset be already published in Exchange or is the user uploading the asset?

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +. If you are creating an API type other than HTTP, upload the specification file in the *File upload* field.
Upload of Asset is only required if they are using the "Create New API" flow. If they are managing from Exchange, user is searching on their Exchange Assets.

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +// . From *Asset Version*, select the Exchange asset version.
What is this `// .` format for?
Is it a comment of something to be removed?

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +* Basic Endpoint: Configure a basic endpoint if you create your API outside API Manager, but want to apply policies or otherwise manage the API using API Manager. For example, if you create the API u
Here is a description of "Basic Endpoint" vs "Endpoint with Proxy"
https://docs.mulesoft.com/api-manager/2.x/configure-api-task

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/create-instance-task.adoc
> +You must install the API gateway domain in Mule 3.8 and later.
This is only if using Reference User Domain

2020-06-22 19:34 UTC, sbehrends commented on modules/ROOT/pages/manage-exchange-api-task.adoc
> +. In *Managing Type*, choose *Basic Endpoint* or *Endpoint with Proxy*:
Same feedback as above.

2020-07-01 16:49 UTC, closed without merging

2020-07-01 16:49 UTC, priyaayyar commented
Created a separate PR for this topic.