DOCS-10394 added content for rest validator extension
mulesoft/docs-api-manager pull request #343
Opened 2021-03-12 16:11 UTC by priyaayyar

2021-03-12 18:45 UTC, LorenaSoledad approved these changes

2021-03-12 19:06 UTC, LorenaSoledad submitted a review, later dismissed

2021-03-15 16:24 UTC, kbostrom approved these changes, later dismissed
CE

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The REST validator extension enables you to perform schema validations against the attributes of a request using a RAML or OAS specification. Additionally, the extension adds default values to attrib
Does "using" refer to the validations  ("that use") or to "you" ("by using")?

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The REST validator extension enables you to perform schema validations against the attributes of a request using a RAML or OAS specification. Additionally, the extension adds default values to attrib
To avoid past tense, how about "...attributes if they are not already set"?

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +This documentation exclusively applies to REST validator extension v2.x. Concepts that do not apply to versions later than 2.x are appropriately noted.
```suggestion
This documentation applies exclusively to REST validator extension v2.x. Concepts that do not apply to versions later than 2.x are appropriately noted.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +This documentation exclusively applies to REST validator extension v2.x. Concepts that do not apply to versions later than 2.x are appropriately noted.
OR...
```suggestion
Unless otherwise noted, this documentation applies exclusively to REST validator extension v2.x.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +
Are the following list items chronological? If not, use bullets instead.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +
The following four items are complete sentences, so they should each end with a period.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Include dependencies in Your pom.xml File
```suggestion
== Include Dependencies in Your pom.xml File
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +You can include the REST validator in your Mule artifact, for example, a Mule application XML, by adding the following snippet in the `<dependencies>` section of your pom.xml file:
```suggestion
You can include the REST validator in your Mule artifact (for example, Mule application XML) by adding the following snippet in the `<dependencies>` section of your `pom.xml` file:
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +As a best practice, you can define a Maven property inside the <properties> section, with the version of the REST validator that you want to use, for example:
Per style ref., avoid "best practice" language and use of modals like "can."

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +As a best practice, you can define a Maven property inside the <properties> section, with the version of the REST validator that you want to use, for example:
```suggestion
Define a Maven property inside the `<properties>` section, with the version of the REST validator that you want to use:
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Configure REST Validator Extension
```suggestion
== Configure the REST Validator Extension
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +To configure the REST Validator, add the following snippet in your Mule artifact:
Use "syntax" rather than "snippet"?
"snippet" refers more to the length of something than to what it actually is, and it might not be immediately familiar to nonnative English readers.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +To configure the REST Validator, add the following snippet in your Mule artifact:
REST Validator extension or REST validator extension? It's lowercase later.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Use REST Validator Operations
operations or operation?
Plural here, singular next

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +
We don't currently have a style for inline bold headings like these.
Consider using a bullet list for these...what would you call these items?

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +Validates request against the specified RAML or OAS specification in the configuration.
Do not use "shorthand" style abbreviated text that omits articles (a or the) before nouns:
```suggestion
Validates a request against the specified RAML or OAS specification in the configuration.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The following table lists the attributes and their descriptions:
The table does not list the attributes and [list] their descriptions; it lists the attributes and describes them.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `attributes` | A DataWeave expression used to extract the attributes that need to be validated. Default value: #[attributes] | No
active voice
```suggestion
| `attributes` | A DataWeave expression that extracts the attributes to validate. Default value: #[attributes] | No
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `payload` | A DataWeave expression used to extract the payload that needs to be validated Default value: #[payload] | No
```suggestion
| `payload` | A DataWeave expression that extracts the payload to validate. Default value: #[payload] | No
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If the request does not violate the defined schema, the validation ends successfully and the result of the operation does not modify the HTTP request attributes. Conversely, default values are added
parallelism, no comma
```suggestion
If the request does not violate the defined schema, the validation ends successfully and the result of the operation does not modify the HTTP request attributes. Conversely, default values are added to the schema validation and the output includes the original and new HTTP request attributes.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:BAD_REQUEST`: Error raised when some of the attributes do not match with the schema. The attributes that are considered during the validation include:
```suggestion
* `REST-VALIDATOR:BAD_REQUEST`
+
Error raised when some of the attributes do not match the schema. The attributes that are considered during the validation include:
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +** URI Parameters
```suggestion
** Form parameters
** Headers
** Query parameters
** URI parameters
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:METHOD_NOT_ALLOWED`: Error raised when the schema does not support a particular method for the required resource.
```suggestion
* `REST-VALIDATOR:METHOD_NOT_ALLOWED`
+
Error raised when the schema does not support a particular method for the required resource.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:RESOURCE_NOT_FOUND`: Error raised when the root schema or some related file cannot be retrieved.
```suggestion
* `REST-VALIDATOR:RESOURCE_NOT_FOUND`
+
Error raised when the root schema or some related file cannot be retrieved.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The following table lists the attributes that you configure for your validator extension:
```suggestion
The following table describes the attributes that you configure for your validator extension:
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `name` | A unique identifier for your configuration | Yes
If you mix fragments and complete sentences in one table column, then all texts in the column must end with periods.
```suggestion
| `name` | A unique identifier for your configuration. | Yes
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* AUTO (default): APIKit attempts to initiate the validation using AMF. If errors are generated, the RAML Parser is used for the validation.
bullet format, active voice:
```suggestion
* AUTO (default)
+
APIKit attempts to initiate the validation using AMF. If errors occur, the RAML parser performs the validation.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* RAML: The APIKit router uses the RAML parser to read the API and validate incoming requests. | No
ditto re. bullet-list format specified by style reference

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `keepApiBaseUri` | Specifies whether  the `baseUri` property in the specification must be overridden with the URI of the deployed application.
Consider rewording to avoid "must be overridden."

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If you need to use the console operation, you must set this property to "true". The default value is false.
```suggestion
If you must use the console operation, set this property to `true`. The default value is `false`.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If you are using a REST validator version that is older than 2.0.0, you must use the `keepRamlBaseUri` attribute. | No
```suggestion
If you are using a REST validator version later than 2.0.0, use the `keepRamlBaseUri` attribute. | No
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `queryParamsStrictValidation` | Validates whether all the query parameters in the request are defined in the specification file.  If some of the parameters are not specified, the validation fails.
GLOBALLY change format of values to use syntax font.

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| attributesDeserializingStrategies` | Allows parsing of the HTTP headers that contain an array of values, separated by a delimiter (comma). | No
```suggestion
| attributesDeserializingStrategies` | Allows parsing of HTTP headers that contain an array of values that are separated by commas. | No
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +You can share the REST validator (pom.xml dependency) across applications using a domain. However, if some of those applications also have a dependency on APIKit, that version of APIKit in each appli
```suggestion
You can share the REST validator (`pom.xml` dependency) across applications by using a domain. However, if some of those applications also have a dependency on APIKit, that version of APIKit in each application must match the one required by the REST validator version that you use in your domain.
```

2021-03-15 16:24 UTC, kbostrom commented on modules/ROOT/pages/rest-validator-extension.adoc
> +For example, if you use the REST validator v2.2.0 in your domain, all your applications using APIKit must import the 1.4.2 version. The following table lists the APIKit module versions that are compa
This example is not obvious until after the table of compatible versions. Consider something like...:
```suggestion
Per the following table of compatibilities, for example, if you use the REST validator v2.2.0 in your domain, all your applications using APIKit must import the 1.4.2 version:
```

2021-03-15 18:12 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The REST validator extension enables you to perform schema validations against the attributes of a request using a RAML or OAS specification. Additionally, the extension adds default values to attrib
Done! Thanks!

2021-03-15 18:13 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +This documentation exclusively applies to REST validator extension v2.x. Concepts that do not apply to versions later than 2.x are appropriately noted.
Done! Thanks!

2021-03-15 18:13 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +
Done! Thanks!

2021-03-15 18:14 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Include dependencies in Your pom.xml File
Done! Thanks!

2021-03-15 18:14 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +You can include the REST validator in your Mule artifact, for example, a Mule application XML, by adding the following snippet in the `<dependencies>` section of your pom.xml file:
Done! Thanks!

2021-03-15 18:15 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +As a best practice, you can define a Maven property inside the <properties> section, with the version of the REST validator that you want to use, for example:
Done! Thanks!

2021-03-15 18:16 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Configure REST Validator Extension
Done! Thanks!

2021-03-15 18:17 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +To configure the REST Validator, add the following snippet in your Mule artifact:
Done! Thanks!

2021-03-15 18:18 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +== Use REST Validator Operations
Done! Thanks!

2021-03-15 18:18 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +Validates request against the specified RAML or OAS specification in the configuration.
Done! Thanks!

2021-03-15 18:20 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The following table lists the attributes and their descriptions:
The following table lists the attributes and provides their descriptions: Done! Thanks!

2021-03-15 18:21 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `attributes` | A DataWeave expression used to extract the attributes that need to be validated. Default value: #[attributes] | No
Done! Thanks!

2021-03-15 18:22 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `payload` | A DataWeave expression used to extract the payload that needs to be validated Default value: #[payload] | No
Done! Thanks!

2021-03-15 18:23 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If the request does not violate the defined schema, the validation ends successfully and the result of the operation does not modify the HTTP request attributes. Conversely, default values are added
Done! Thanks!

2021-03-15 18:25 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:BAD_REQUEST`: Error raised when some of the attributes do not match with the schema. The attributes that are considered during the validation include:
Done! Thanks!

2021-03-15 18:25 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +** URI Parameters
Done! Thanks!

2021-03-15 18:25 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:METHOD_NOT_ALLOWED`: Error raised when the schema does not support a particular method for the required resource.
Done! Thanks!

2021-03-15 18:26 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* `REST-VALIDATOR:RESOURCE_NOT_FOUND`: Error raised when the root schema or some related file cannot be retrieved.
Done! Thanks!

2021-03-15 18:26 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +The following table lists the attributes that you configure for your validator extension:
Done! Thanks!

2021-03-15 18:27 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `name` | A unique identifier for your configuration | Yes
Done! Thanks!

2021-03-15 18:28 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* AUTO (default): APIKit attempts to initiate the validation using AMF. If errors are generated, the RAML Parser is used for the validation.
Done! Thanks!

2021-03-15 18:28 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +* RAML: The APIKit router uses the RAML parser to read the API and validate incoming requests. | No
Done! Thanks!

2021-03-15 18:29 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `keepApiBaseUri` | Specifies whether  the `baseUri` property in the specification must be overridden with the URI of the deployed application.
Done! Thanks!

2021-03-15 18:29 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If you need to use the console operation, you must set this property to "true". The default value is false.
Done! Thanks!

2021-03-15 18:30 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +If you are using a REST validator version that is older than 2.0.0, you must use the `keepRamlBaseUri` attribute. | No
Done! Thanks!

2021-03-15 18:31 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `queryParamsStrictValidation` | Validates whether all the query parameters in the request are defined in the specification file.  If some of the parameters are not specified, the validation fails.
Done! Thanks!

2021-03-15 18:32 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| attributesDeserializingStrategies` | Allows parsing of the HTTP headers that contain an array of values, separated by a delimiter (comma). | No
Done! Thanks!

2021-03-15 18:33 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +You can share the REST validator (pom.xml dependency) across applications using a domain. However, if some of those applications also have a dependency on APIKit, that version of APIKit in each appli
Done! Thanks!

2021-03-15 18:34 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +For example, if you use the REST validator v2.2.0 in your domain, all your applications using APIKit must import the 1.4.2 version. The following table lists the APIKit module versions that are compa
Done! Thanks!

2021-03-15 20:41 UTC, LorenaSoledad requested changes

2021-03-15 20:41 UTC, LorenaSoledad commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `api` | If you are using a version of the REST validator later than 2.0.0, you must use the `raml` attribute. This includes the location of the specification file against which the requests are to
`api` is a required attribute.

2021-03-15 21:51 UTC, priyaayyar commented on modules/ROOT/pages/rest-validator-extension.adoc
> +| `api` | If you are using a version of the REST validator later than 2.0.0, you must use the `raml` attribute. This includes the location of the specification file against which the requests are to
Done! Thanks!

2021-03-15 21:54 UTC, LorenaSoledad approved these changes

2021-03-15 22:21 UTC, kbostrom approved these changes
RA

2021-03-15 23:39 UTC, merged