DOCS-10854 fixed the error descriptions and codes
mulesoft/docs-api-manager pull request #366
Opened 2021-05-14 19:09 UTC by priyaayyar

2021-05-14 21:04 UTC, LorenaSoledad submitted a review, later dismissed

2021-05-14 23:24 UTC, IsaacEldridge requested changes

2021-05-14 23:24 UTC, IsaacEldridge commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +.3+>.^! 401 ! Signature was not validated, or is invalid.. ! Some of the required claims are not present or their validation failed.
extra period?

2021-05-15 00:15 UTC, priyaayyar commented on modules/ROOT/pages/policy-mule4-jwt-validation.adoc
> +.3+>.^! 401 ! Signature was not validated, or is invalid.. ! Some of the required claims are not present or their validation failed.
Good catch! Done! Thanks!

2021-05-17 15:35 UTC, IsaacEldridge approved these changes

2021-06-17 23:56 UTC, merged