SE-22323: Update header removal policy doc
mulesoft/docs-api-manager pull request #398
Opened 2021-08-19 18:50 UTC by pablogomez93

2021-08-19 19:06 UTC, JaatadiaMulesoft submitted a review, later dismissed

2021-08-20 13:36 UTC, JaatadiaMulesoft submitted a review, later dismissed

2021-09-07 21:08 UTC, priyaayyar requested changes

2021-09-07 21:08 UTC, priyaayyar commented on modules/ROOT/pages/header-removal-policy.adoc
> +For example, the following parameter configuration removes the `Access-Control-Allow-Credentials` header from a message but also any other starting with `Access-Control` (like `Access-Control-Allow-O
```suggestion
For example, the following parameter configuration removes any header starting with the word `Access-Control`, such as the `Access-Control-Allow-Credentials` and `Access-Control-Allow-Origin` headers from a message. The configuration also removes the `Cache-Control` header:
```

2021-09-08 15:38 UTC, emileeburkeVT approved these changes

2021-09-08 15:42 UTC, priyaayyar approved these changes

2021-09-08 15:46 UTC, merged