Improve Gateway articles based on user feedback
mulesoft/docs-api-manager pull request #43
Opened 2019-01-02 15:19 UTC by fermujica

2019-01-02 17:00 UTC, nahuel-dallavecchia requested changes

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +. When you deploy or update an already deployed application on the Runtime Manager, include your client ID and client secret as environment variables.
It should be on Runtime Manager instead of on *the* Runtime Manager.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +. When you deploy or update an already deployed application on the Runtime Manager, include your client ID and client secret as environment variables.
It would be good to add a link here to actual configuration details as in https://docs.mulesoft.com/api-manager/2.x/org-credentials-config-mule3 and https://docs.mulesoft.com/api-manager/2.x/org-credentials-config-mule4. Take into account, for rxample, that for EU plane you need to also specify the base URL.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +* Open the Advanced section and define two Environment Variables with your Anypoint Platform client ID and client secret, which you can obtain from an Organization Administrator.
This way of specifying the values only applies to Cloudhub.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
*the* API Manager.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
other ~kinds~ types of endpoints

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
It should be clear that API Gateway can only be used with HTTP(s) endpoints for now.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +If you are using Mule runtime 3.7.x or below along with an API Gateway instance, and you need to access API Manager through a proxy, you can follow these instructions to configure API Gateway channel
This functionality only applies to API Gateway, that means runtime 3.8.0 or later, or API Gateway 2.x.x.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +If you are using Mule runtime 3.7.x or below along with an API Gateway instance, and you need to access API Manager through a proxy, you can follow these instructions to configure API Gateway channel
Not clear "configure API Gateway channel all its' communications"

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +Follow the xref:configuring-an-api-gateway.adoc#setting-up-an-on-premises-gateway[Configuring A Production API Gateway for Integration with Anypoint Platform] instructions to learn how to do this. +
Corresponding "Configuring Organization Credentials" has more details.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
>  <MULE_HOME> is the value of the MULE_HOME variable, usually the root directory of the Mule installation, such as `/opt/Mule/api-gateway-2.0.0/`
The path in the example correspond to deprecated API Gateway version, it would be better to use latest runtime 3.x or 4.x as an example.

2019-01-02 17:00 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +----
If you are using Mule 4, in addition to the mentioned parameters, usually, you would need something to disable HTTPs certificate validation, since many proxies do not have a valid certificate configured.

2019-01-02 17:01 UTC, Mulesoft-Mysti approved these changes
A couple of grammar nits, otherwise looks great!
You should be able to merge after edits with this approval.
I didn't test the links.

2019-01-02 17:01 UTC, Mulesoft-Mysti commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +* Open the Advanced section and define two Environment Variables with your Anypoint Platform client ID and client secret, which you can obtain from an Organization Administrator.
lower case for environment variables.

2019-01-02 17:01 UTC, Mulesoft-Mysti commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
change one of the two "full" to a different word.

2019-01-02 17:01 UTC, Mulesoft-Mysti commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +If you are using Mule runtime 3.7.x or below along with an API Gateway instance, and you need to access API Manager through a proxy, you can follow these instructions to configure API Gateway channel
delete "you can"
no apostrophe on its (it's the possessive form, not the contraction for "it is")

2019-01-03 21:29 UTC, fermujica commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
Dropping the `the`s for the API gateway and API Manager: 7e4d0b9

Regarding: 
> It should be clear that API Gateway can only be used with HTTP(s) endpoints for now

Should I drop mentions of Web Service Consumer?

2019-01-03 21:29 UTC, fermujica commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +* Open the Advanced section and define two Environment Variables with your Anypoint Platform client ID and client secret, which you can obtain from an Organization Administrator.
Yes. This is under the **Manual Deployment to CloudHub** title.

2019-01-03 21:29 UTC, fermujica commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +. When you deploy or update an already deployed application on the Runtime Manager, include your client ID and client secret as environment variables.
I missed this one. 
See 3560c09

2019-01-03 21:43 UTC, fermujica commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +If you are using Mule runtime 3.7.x or below along with an API Gateway instance, and you need to access API Manager through a proxy, you can follow these instructions to configure API Gateway channel
I rewrote this in 427d457

2019-01-03 21:47 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-an-api-gateway.adoc
> +You can use the API Gateway to run your existing services with HTTP/HTTPS or Web Service Consumer connectors to the API Manager. You can also include selected additional connectors, as specified in y
I would advise dropping the Web Service Consumer connector statement, since its not supported.

2019-01-03 21:52 UTC, nahuel-dallavecchia requested changes

2019-01-03 21:52 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +Follow the xref:configuring-an-api-gateway.adoc#setting-up-an-on-premises-gateway[Configuring A Production API Gateway for Integration with Anypoint Platform] instructions to learn how to do this. +
Can you add a link to it?

2019-01-03 21:52 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +----
Can you add the key anypoint.platform.enable_ssl_validation for the Mule 4 scenario?

2019-01-03 21:52 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
>  <MULE_HOME> is the value of the MULE_HOME variable, usually the root directory of the Mule installation, such as `/opt/Mule/api-gateway-2.0.0/`
Can you update the path?

2019-01-04 20:18 UTC, fermujica commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +Follow the xref:configuring-an-api-gateway.adoc#setting-up-an-on-premises-gateway[Configuring A Production API Gateway for Integration with Anypoint Platform] instructions to learn how to do this. +
This article is part of the API Manager 2.x. 
It looks like those instructions are valid for pre-crowd API Manager as well. I can bring those instructions back to 1.x and link to it.

2019-01-04 20:19 UTC, fermujica commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +----
Is API Manager 1.x compatible with Mule 4? These changes are meant to quickly fix some "archived" labels from the 1.x docs.

2019-01-04 20:32 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +----
Ah! If only for runtimes < Mule 4, then disregard comment.

2019-01-04 20:38 UTC, nahuel-dallavecchia commented on modules/ROOT/pages/configuring-proxy-access-to-an-api.adoc
> +Follow the xref:configuring-an-api-gateway.adoc#setting-up-an-on-premises-gateway[Configuring A Production API Gateway for Integration with Anypoint Platform] instructions to learn how to do this. +
Umm. The instructions are valid for Pre Crowd, except for the environments part. You may copy the article, removing any reference to environments and it should work. Considering that this is a Pre Crowd organization documentation, I'll leave it to you to decide wheter improve the doc or not.

2019-01-04 20:40 UTC, nahuel-dallavecchia approved these changes
Some pending minor stuff to fix, but considering it applies to pre Crowd type organizations, it's not critical.

2019-01-04 20:42 UTC, merged