Update promote-api-task.adoc
mulesoft/docs-api-manager pull request #538
Opened 2023-09-25 22:20 UTC by kevinzlu-salesforce

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-09-26 15:05 UTC, glenn-rodgers-sf requested changes

2023-09-26 15:05 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/promote-api-task.adoc
>  Promoting an API affects only the API definition, not the existing deployed applications subscribed to the API. After promoting an API, the API Name remains the same, but the API ID changes.
```suggestion
Promoting an API instance affects only the API definition, not the existing deployed applications subscribed to the instance. After promoting an API, the *API Label* remains the same, but the *API Instance ID* changes.
```

2023-09-26 15:05 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/promote-api-task.adoc
> +For existing applications that need to subscribe to a promoted API:
```suggestion
For existing applications that must subscribe to a promoted API instance:
```

2023-09-26 15:05 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/promote-api-task.adoc
>  . Update the API ID.
```suggestion
. Update the *API Instance ID* within the application.
```

2023-09-26 15:05 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/promote-api-task.adoc
> +Before promoting an API instance to another environment:
See google doc:

https://docs.google.com/document/d/1_CNwMZhAFZGxBLBNo2VRuKZnmPGAy2-ikd-P5YUrgVE/edit?usp=sharing

2023-10-02 20:38 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/promote-api-task.adoc
> +Before promoting an API instance to another environment ensure that you have the `Manage APIs Configuration` permission.
```suggestion
Before promoting an API instance to another environment, ensure that you have the `Manage APIs Configuration` permission.
```

2023-10-03 21:36 UTC, bjoson-mulesoft approved these changes, later dismissed

2023-10-09 17:25 UTC, juanpjacob approved these changes

2023-10-09 18:45 UTC, hannanelson commented on modules/ROOT/pages/promote-api-task.adoc
> +Before promoting an API instance to another environment, ensure that you have the `Manage APIs Configuration` permission.
I don't think we change fonts for permissions.

2023-10-09 18:45 UTC, hannanelson commented on modules/ROOT/pages/promote-api-task.adoc
> +Before promoting an API instance to another environment, ensure that you have the `Manage APIs Configuration` permission.
https://confluence.internal.salesforce.com/display/MTDT/MuleSoft+CX+Writing+Style+Reference#MuleSoftCXWritingStyleReference-fontchoices

2023-10-09 18:45 UTC, hannanelson commented on modules/ROOT/pages/promote-api-task.adoc
> +You can only promote an entity, such as policies or alerts, if you have both the permissions to view the entity and to manage its destination. For example, you must have the `View Policies` and `Mana
font

2023-10-09 18:47 UTC, hannanelson commented on modules/ROOT/pages/promote-api-task.adoc
>  . Because each environment has a different client ID and secret, update the application's client ID and secret.
```suggestion
. Update the application's client ID and secret.
+
Each environment has a different client ID and secret.
```

2023-10-09 18:47 UTC, hannanelson approved these changes

2023-10-09 21:30 UTC, glenn-rodgers-sf approved these changes

2023-10-09 21:30 UTC, merged